#!/bin/bash

hook_name=$(basename $0)

set -x

exec > ${SNAP_DATA}/hooks.log 2>&1
echo "$(date '+%Y-%m-%d %H:%M:%S'): Entering ${hook_name} hook"
echo "SNAP_REVISION=${SNAP_REVISION}"

# handle fresh istall

# fresh install no need to migrate config, if needed
# snapctl set conf-migrated=true

